//
//  MessagesViewController.swift
//  MovieQuotes MessagesExtension
//
//  Created by Terry Dengis on 1/24/19.
//  Copyright © 2019 Terry Dengis. All rights reserved.
//

import UIKit
import Messages

class MessagesViewController: MSMessagesAppViewController {
    
    @IBOutlet weak var button1: UIButton!
    @IBOutlet weak var button2: UIButton!
    @IBOutlet weak var button3: UIButton!
    @IBOutlet weak var button4: UIButton!
    @IBOutlet weak var button5: UIButton!
    @IBOutlet weak var button6: UIButton!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        button1.imageView?.contentMode = .scaleAspectFill
        button2.imageView?.contentMode = .scaleAspectFill
        button3.imageView?.contentMode = .scaleAspectFill
        button4.imageView?.contentMode = .scaleAspectFill
        button5.imageView?.contentMode = .scaleAspectFill
        button6.imageView?.contentMode = .scaleAspectFill

        // Do any additional setup after loading the view.
    }
    
    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state.
        // This will happen when the extension is about to present UI.
        
        // Use this method to configure the extension and restore previously stored state.
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dissmises the extension, changes to a different
        // conversation or quits Messages.
        
        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.
        
        // Use this method to trigger UI updates in response to the message.
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    
        // Use this to clean up state related to the deleted message.
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.
    
        // Use this method to prepare for the change in presentation style.
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.
    
        // Use this method to finalize any behaviors associated with the change in presentation style.
    }

    @IBAction func movie1(_ sender: Any) {
        
        let template = MSMessageTemplateLayout ()
        template.caption = "I'll be back!"
        template.image = UIImage(named: "Arnold")
        
        let message = MSMessage ()
        message.layout = template
        
        activeConversation?.insert(message, completionHandler: nil)
        requestPresentationStyle(.compact)
    }
    
    @IBAction func movie2(_ sender: Any) {
        
        let template = MSMessageTemplateLayout ()
        template.caption = "I am your father!"
        template.image = UIImage(named: "DarthVader")
        
        let message = MSMessage ()
        message.layout = template
        
        activeConversation?.insert(message, completionHandler: nil)
        requestPresentationStyle(.compact)
    }
    
    @IBAction func movie3(_ sender: Any) {
        
        let template = MSMessageTemplateLayout ()
        template.caption = "Phone home!"
        template.image = UIImage(named: "ET")
        
        let message = MSMessage ()
        message.layout = template
        
        activeConversation?.insert(message, completionHandler: nil)
        requestPresentationStyle(.compact)
    }
    
    @IBAction func movie4(_ sender: Any) {
        
        let template = MSMessageTemplateLayout ()
        template.caption = "Bond, James Bond!"
        template.image = UIImage(named: "JamesBond")
        
        let message = MSMessage ()
        message.layout = template
        
        activeConversation?.insert(message, completionHandler: nil)
        requestPresentationStyle(.compact)
    }
    
    @IBAction func movie5(_ sender: Any) {
        
        let template = MSMessageTemplateLayout ()
        template.caption = "Adrian!"
        template.image = UIImage(named: "Rocky")
        
        let message = MSMessage ()
        message.layout = template
        
        activeConversation?.insert(message, completionHandler: nil)
        requestPresentationStyle(.compact)
    }
    
    @IBAction func movie6(_ sender: Any) {
        
        let template = MSMessageTemplateLayout ()
        template.caption = "Say hello to me little friend!"
        template.image = UIImage(named: "Scarface")
        
        let message = MSMessage ()
        message.layout = template
        
        activeConversation?.insert(message, completionHandler: nil)
        requestPresentationStyle(.compact)
    }
}
